module.exports = {
  name: 'rk-icon',
  basic: ['arrow', 'arrow-left', 'arrow-up', 'arrow-down', 'success', 'cross', 'plus'],
  single: [
    // has corresponding filled icon
    'close',
    'arrow_up-d',
    'arrow-down-d',
    'arrow-right-s',
    'arrow-up-s',
    'arrow-down-s',
    'close-s',
    'info',
    'edit',
    'share',
    'search',
    'refresh',
    'add-round',
    'add-square',
    'minus-round',
    'minus-square',
    'contact',
    'time',
    'time-s',
    'user-s',
    'smartphone',
    'calendar',
    'phone-left-s',
    'phone-right-s',
    'phone-left',
    'phone-right',
    'trash',
    'eye-open-s',
    'eye-closed-s',
    'paper',
    'paper-s',
    'dot-s',
    'speaker-s',
    'recipt-s',
    'luggage-s',
    'id',
    'headphone',
    'techsupport-s',
    'history',
    'scan',
    'checked',
    'clear',
  ],
  multi: [
    // has corresponding outline icon
    'map-full',
    'map-refresh',
    'map-walk',
    'map-location-1',
    'map-location-2',
    'map-arrive',
    'map-depart',
    'map-mid',
    'map-user',
    'map-userdirection',
  ],
};
